### ISSUE TITLE
Detail Graphs are not being created

### ISSUE THREAD

**Issue by Thaddeus-Maximus** [RoseGPE/RoseLapWeb#27]

**Comment by Thaddeus-Maximus** [comment]
outputs are empty, that is why

**Comment by Thaddeus-Maximus** [comment]
fixing that yields a memoryerror

`ERROR:root:Traceback (most recent call last):
  File "c:/wamp/www/RoseLap/py/RoseLapCore/webrunner.py", line 70, in <module>
    dashboarder.make_dashboard(results, bcName, display_dir)
  File "c:\wamp\www\RoseLap\py\RoseLapCore/../RoseLapCharter\dashboarder.py", line 22, in make_dashboard
    summary_plot = heatmap_v2.make_plot(results, display_dir, display_name)
  File "c:\wamp\www\RoseLap\py\RoseLapCore/../RoseLapCharter\heatmap_v2.py", line 96, in make_plot
    plot.write(detail.make_sub_plot(outdata))
  File "c:\wamp\www\RoseLap\py\RoseLapCore/../RoseLapCharter\detail.py", line 24, in make_sub_plot
    return html % (plotter(output), plotter(output, 'time'))
MemoryError
Traceback (most recent call last):
  File "c:/wamp/www/RoseLap/py/RoseLapCore/webrunner.py", line 70, in <module>
    dashboarder.make_dashboard(results, bcName, display_dir)
  File "c:\wamp\www\RoseLap\py\RoseLapCore/../RoseLapCharter\dashboarder.py", line 22, in make_dashboard
    summary_plot = heatmap_v2.make_plot(results, display_dir, display_name)
  File "c:\wamp\www\RoseLap\py\RoseLapCore/../RoseLapCharter\heatmap_v2.py", line 96, in make_plot
    plot.write(detail.make_sub_plot(outdata))
  File "c:\wamp\www\RoseLap\py\RoseLapCore/../RoseLapCharter\detail.py", line 24, in make_sub_plot
    return html % (plotter(output), plotter(output, 'time'))
MemoryError`

**Comment by Thaddeus-Maximus** [comment]
Memory leaks suck. added plt.close(fig) after eaceh figure save.
