### ISSUE TITLE
Fix Steady State sims

### ISSUE THREAD

**Issue by Thaddeus-Maximus** [RoseGPE/RoseLapWeb#33]
we don't have a fair assessment of skidpad points rn

**Comment by Thaddeus-Maximus** [comment]
`2018-07-16 10:31:36,476 | ERROR   : Traceback (most recent call last):
  File "c:/wamp/www/RoseLap/py/RoseLapCore/webrunner.py", line 76, in <module>
    results = batcher.batch(tests, vehicle, tracks, model, out[1] != 0)
  File "c:\wamp\www\RoseLap\py\RoseLapCore\batcher.py", line 21, in batch
    batch["track_data"] = batch_run(flatTargets, permutations, batch["test_vals"], vehicle, tracks, model, include_output)
  File "c:\wamp\www\RoseLap\py\RoseLapCore\batcher.py", line 178, in batch_run
    thread_results = [run_permutation(d) for d in thread_data]
  File "c:\wamp\www\RoseLap\py\RoseLapCore\batcher.py", line 94, in run_permutation
    time = index + (float(data[-1, constants.O_TIME]),)
TypeError: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "c:/wamp/www/RoseLap/py/RoseLapCore/webrunner.py", line 76, in <module>
    results = batcher.batch(tests, vehicle, tracks, model, out[1] != 0)
  File "c:\wamp\www\RoseLap\py\RoseLapCore\batcher.py", line 21, in batch
    batch["track_data"] = batch_run(flatTargets, permutations, batch["test_vals"], vehicle, tracks, model, include_output)
  File "c:\wamp\www\RoseLap\py\RoseLapCore\batcher.py", line 178, in batch_run
    thread_results = [run_permutation(d) for d in thread_data]
  File "c:\wamp\www\RoseLap\py\RoseLapCore\batcher.py", line 94, in run_permutation
    time = index + (float(data[-1, constants.O_TIME]),)
TypeError: 'NoneType' object has no attribute '__getitem__'`

**Comment by Thaddeus-Maximus** [comment]
that error actualyl relates to failed runs
